import type { Metadata } from "next";
import {Montserrat} from "next/font/google"
import "./globals.css";
import ToastProvider from "../toast/toastContainer";

const montserrat = Montserrat({
  weight: "400",
  style: "normal",
  subsets: ["latin"]
})
export const metadata: Metadata = {
  title: "Medaussie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={montserrat.className}
      >
        <ToastProvider>
        {children}
        </ToastProvider>
      </body>
    </html>
  );
}
